# Enable Theebe
launch_buttons:
  thebe: true
  notebook_interface: "jupyterlab"

thebe_config:
  use_thebe: true
  binderhub_url: ""  # leave empty
  kernel_options:
    kernelName: "python3"
    serverSettings:

sphinx:
  config:
    html_static_path: ["_static"]
    html_js_files:
      - _static/thebe-local-config.html
      - https://unpkg.com/thebe@latest
